import type { Metadata } from "next";
import { Rubik, Open_Sans } from "next/font/google";
const rubik = Rubik({
  subsets: ["latin"],
  variable: "--rubik",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});
const open_sans = Open_Sans({
  subsets: ["latin"],
  variable: "--open-sans",
  display: "swap",
  weight: ["300", "400", "500", "700"],
});
import "../styles/styles.scss";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${open_sans.variable} ${rubik.variable}`}>
        {children}
      </body>
    </html>
  );
}
